language: java
before_script:
  - cat /etc/hosts
  - echo 127.0.0.1 localhost > /etc/hosts

install: mvn install -Dgpg.skip=true
jdk:
  - openjdk6
  - openjdk7
  - oraclejdk7

notifications:
  email:
    recipients:
      - hendrikdev22@gmail.com
    on_success: always
    on_failure: always
