language: java

jdk:
  - openjdk6
  - openjdk7
  - oraclejdk7

before_script:
    # replace localhost.localdomain
    - sudo apt-get update
    - sudo sed -i "s/localhost.localdomain//" /etc/hosts

install: mvn install -Dgpg.skip=true

notifications:
  email:
    recipients:
      - hendrikdev22@gmail.com
    on_success: always
    on_failure: always
