language: java

jdk:
  - openjdk6
  - openjdk7
  - oraclejdk7

before_script:
  - echo -e "\n\n>>> Building ..."
  - sh -c "echo building 2"
  - sudo cat /etc/hosts
  - sudo sed -i"s/localhost.localdomain//" /etc/hosts
  - sudo cat /etc/hosts
  - echo -e "\n\n>>> End ..."

install: mvn install -Dgpg.skip=true

notifications:
  email:
    recipients:
      - hendrikdev22@gmail.com
    on_success: always
    on_failure: always
